apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    iam.gke.io/gcp-service-account: "trading-app@{{ .Values.env.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
